version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-24-alpha
    working_directory: ~/app
    environment:
      TERM: dumb
      KEYSTORE: /home/circleci/app/signing.keystore
    steps:
      - checkout
      - restore_cache:
          key: ndk-bundle
      - run: sdkmanager ndk-bundle
      - save_cache:
          paths:
            - /opt/android/sdk/ndk-bundle/
          key: ndk-bundle
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: bash ./.circleci/keystore-setup.sh
      - run:
          name: Assemble Stable Release
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/